### PR TITLE
Fix problem with initialization

### PR DESCRIPTION
**Pull request by peterM**
Fix problem #104

### CODE REVIEW

**Comment by Mahsaap** [comment]
gonna break VB support doing this.

**Comment by peterM** [comment]
What is 'VB' ?
Problem is that user type from constructor was is ignored and instead of this classes property is initialized from the self instead of from incoming `ctor` parameter

**Comment by Mahsaap** [comment]
visual basic

**Comment by swiftyspiffy** [comment]
Hey, sorry for the month delay on this. Can you target the dev branch on this PR?

**Comment by peterM** [comment]
Hi @swiftyspiffy no problem. I see that PR is already merged. Should i still create another PR and target `dev` branch ?

**Pull request merged**
