### PR TITLE
Parsing Rewrite and some cleanup

### PR DESCRIPTION
**Pull request by Syzuna**
Reviews and some deep views are wanted. This is a critical part of the lib so try to find any errors you can think of

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Added reviewers since permissions dont seem to allow the submitter to add reviewers

**Comment by LuckyNoS7evin** [comment]
Initially looks okay. I may download your fork @Syzuna and run a test bot if you don't mind. All the changes look amazing on the surface and make the whole codebase a lot neater.

So again the code looks good but would like to test it...

**Comment by Syzuna** [comment]
Thats what I asked for Lucky :D I tested it a test branch of my bot and didnt find any problems anymore but yes I would appreciate more testing from others

**Comment by swiftyspiffy** [comment]
I’m of the same mindset as Lucky. Will implement this library in Burke’s bot and let it run to see if we encounter any issues.

**Comment by Syzuna** [comment]
Thats why I said more testing is appreciated :D

**Pull request merged**
