### PR TITLE
Started changes for the new msgParams Subscriptions

### PR DESCRIPTION
**Pull request by Mahsaap**
AnonGift
GiftSub
Tags

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Gonna merge this and fix it up as needed.

**Comment by swiftyspiffy** [comment]
Actually this is master. Going to close and recreate it for dev.

**Comment by Mahsaap** [comment]
@swiftyspiffy did this ever get done? doesnt seem to have any of these ihn master or dev atm

**Comment by Mahsaap** [comment]
@swiftyspiffy do I need to redo this?

**Comment by MopsiMauser** [comment]
The changes for the msgParams regarding subscriptions also have to be applied in the SubscriberBase and ReSubscriber classes.

**Comment by Mahsaap** [comment]
obsolete / was rebased for dev branch by swift a while ago.

**Pull request closed without merging**
