### PR TITLE
IsConnected uses _client that was null before initialization.

### PR DESCRIPTION
**Pull request by kamyker**
Tbh Connect(credentials) would be more intuitive. Right now to change credentials I would have to Disconnect, change credentials and use Reconnect() function?? Seems like Connect() doesn't update WebSocket and use old one from initialization.

### CODE REVIEW

**Comment by swiftyspiffy** [comment]
Hey @kamyker !

I agree with your reasoning, but let me run this past the team members first.

**Comment by swiftyspiffy** [comment]
So after reviewing this a second time (as well as with others), I don't think this will work. The setter in this case gets invoked before the _initialized variable has been set to true, which would always result in an exception being thrown.

**Comment by Syzuna** [comment]
Actually your change wont work bcs _initialized will never be true on the first set of the ConnectionCredentials and bcs of this would error everytime.

**Comment by kamyker** [comment]
Yes, this change doesn't fix "not being able to change credentials on first run", it was meant to just inform user that he has to init before changing it. 
Basically I tried that, got null and didn't know why.  With that exception it's easier to fix it.

**Comment by swiftyspiffy** [comment]
I think we want to go a different direction than this. The goal of having a Connect method without parameters is that it'd do exactly one thing: connect. The initialize method should handle all of the initial settings of client properties.

**Comment by Syzuna** [comment]
I second that swifty.

Using the client as intended would be the easiest way.
But yeah the initialized boolean cant be used internally.
Exposing it as public is sth we can do. This would bring the Dev into resposibility tho although I dont see a problem with doing that.

**Comment by swiftyspiffy** [comment]
Though I'm not sure what kind of use case would warrant needing to create the Client, not call the Initialize method, and then need to check if the client has been initialized.

**Comment by Syzuna** [comment]
I dont know.

He is right in one thing tho. the IsConnected will break if the Initialize method wasnt called prior to trying to set the credentials manually. why you wanna even do that I dont know

**Comment by kamyker** [comment]
"The flow should be similar to what you state:

Disconnect();
Access ConnectionCredentials setter (will throw exception if IsConnected)
Connect();"
Currently this doesn't work as ConnectionCredentials setter doesn't change websocket created in Initialize.

**Comment by Syzuna** [comment]
Its not in the constructor anymore bcs of DI reasons

**Comment by swiftyspiffy** [comment]
`Currently this doesn't work as ConnectionCredentials setter doesn't change websocket created in Initialize.`
The setter for ConnectionCredentials should only modify ConnectionCredentials, right? Otherwise I think we'd be misusing it. The core problem here seems to be that the Disconnect call needs to be improved? 
If Disconnect() was async, it'd allow you to manipulate the websocket client in a relatively unknown state (ie not completely disconnected - 200ms wait), which would cause other problems right? Unless of course you access the IsConnected bool to check if the client's state is able to be safely modified.

`Btw what's the reason to not initialize a client in constructor? Just curious as that is the case in nuget version.`
It was originally like this, but dependency injection is more friendly when we have a method that initializes the client, and a separate method that does just connecting.

`Let's say someone didn't read docs and he doesn't know how to "use the client as intended". (Like me as docs don't exist for new version yet.) He may try doing something like this:`
This is a problem that needs to be addressed. There are basically no docs for the recent changes that have been made.

`He get's null and doesn't know why. It's easy to figure that out with source code or docs but it should be possible without both of them.`
In theory, once the proper documentation exists, this shouldn't be a problem. More detailed exceptions could be implemented, I think.

**Pull request closed without merging**
