### PR TITLE
Emote set count zero fix

### PR DESCRIPTION
**Pull request by RRickkert**
Previously the EmoteSet was created before the message was parsed, meaning _emoteSetStorage would always be null, resulting in the EmoteSet being empty, which then again results in the EmoteSet having "EmoteSet.Emotes.Count" being 0.

This is a fix for #405 https://github.com/TwitchLib/TwitchLib/issues/405 

This does raise a question: Why is the instance of EmoteSet not being created in the switch Case, just like in the WhisperMessage? This seems to work just fine (see commit).

### CODE REVIEW

**Comment by RRickkert** [comment]
Should also fix "Client.OnMessageReceivedArgs not holding any emote data" from issue #42

**Comment by LeXtruX** [comment]
I get my version through Visual Studio's NuGet, it does not seem that this fix is not available there

**Comment by Mahsaap** [comment]
Nuget is master branch of the git repo. This has been aplied to dev branch.

**Comment by swiftyspiffy** [comment]
@LeXtruX Possibly as early as tomorrow, but definitely this week I think.

**Pull request merged**
