### PR TITLE
Bring builders to improve create process of model instances

### PR DESCRIPTION
**Pull request by peterM**
Bring builders to improve create process of model instances.

Especially in testing could be beneficial to have builders.

This pr is from #103  but targeting dev branch
Issue #102 

Builders and more
- Reformat documents to be better readable
- Add concept to extract logic out of the model (`Extractors`)

### CODE REVIEW

**Comment by Mahsaap** [comment]
Just a kindly request. Next time you do a PR please wait till your finished. I think I have about 50 emails in the last 2 days. :) Appreciate all the work.

**Comment by peterM** [comment]
@Mahsaap  sorry for that :/ I'll try to do less pushes.
Btw.: i found lot of small defects i'll fix them in this PR

**Comment by Mahsaap** [comment]
np, anything you find sure, just make sure your working off the dev branch. master is way behind. we are also on discord if you ever wanted to talk about things.

**Comment by peterM** [comment]
@Mahsaap I will check also discord.
I am new to open source so sorry if i do /did something wrong :( it is not intentional.

**Comment by Mahsaap** [comment]
I'll be honest I scrolled through, so I didn't look closely but for what I can see awesome work. 👍

**Comment by peterM** [comment]
> I'll be honest I scrolled through, so I didn't look closely but for what I can see awesome work. 👍

thanks :)

**Comment by swiftyspiffy** [comment]
Hey @peterM this is a pretty large PR. Can you rebase/fix the conflicts that resulted from merging @Mahsaap 's PR, and then I'll have a look at it.

Thanks!

**Comment by peterM** [comment]
@swiftyspiffy PR should be aligned now

**Comment by swiftyspiffy** [comment]
Awaiting confirmation from the build, then merging.

**Pull request merged**
