### PR TITLE
add onPrimePaidSubscriber to ITwitchClient.cs

### PR DESCRIPTION
**Pull request by Moerty**

### CODE REVIEW

**Comment by Syzuna** [comment]
Could you please target the dev branch? thanks for catching that

**Comment by Moerty** [comment]
Done. Added more missing events.
Should I recreate this pullrequests with correct source / target branch or can you merge it like that?

**Comment by AoshiW** [comment]
The changes from this PR are already in the dev branch, so this PR can be closed

**Comment by swiftyspiffy** [comment]
Out of date

**Pull request closed without merging**
